<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
   <meta charset="utf-8">
   <title></title>
    <link rel="stylesheet" href="../CSS/style.css">

 </head>
 <body>

    <div id="footer_admin" class="div_footer">
    <footer class="flex-rw">
<section class="footer-bottom-section flex-rw">
   <div class="footer-bottom-wrapper">
     <div class="footer-address">
     <p id="css_validar">
      <a href="http://jigsaw.w3.org/css-validator/check/referer">
        <img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="¡CSS Válido!" />
      </a>
     </p>

    <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
       <img class='footer-address_img' alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" />
    </a>
<br />

    </div>
     <div class="footer-address">
         <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Surface</span>by
         <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Daniel González González</span>
         is licensed under a
         <a class="cretive_commons" rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
         Creative Commons Reconocimiento-NoComercial 4.0 Internacional License
         </a>.
      </div>
    </div>
  </section>
</footer>
</div>

   <?php mysqli_close($connect) ?>

</body>
</html>
