<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="cuadro_final"></div>
      <div class="div_footer">

        <footer class="flex-rw">

    <ul class="ul_footer footer-list-top">
      <li>
        <h4 class="footer-list-header">Nosotros</h4></li>
      <li><a href='contactoRegistrado.php' class="generic-anchor footer-list-anchor">CONTACTANOS</a></li>
      <li><a href='indexRegistrado.php' class="generic-anchor footer-list-anchor">INICIO</a></li>
      <li><a href='tiendaRegistrado.php#nov' class="generic-anchor footer-list-anchor">NOVEDADES</a></li>
    </ul>
    <ul class="ul_footer footer-list-top">
      <li>
        <h4 class="footer-list-header">Tienda Online</h4></li>


      <li><a href='tiendaRegistrado.php' class="generic-anchor footer-list-anchor">TIENDA</a></li>
      <li><a href='tiendaRegistrado.php#tabl' class="generic-anchor footer-list-anchor">TABLAS</a></li>
      <li><a href='tiendaRegistrado.php#neop' class="generic-anchor footer-list-anchor">NEOPRENOS</a></li>
    </ul>
    <ul class="ul_footer footer-list-top">
      <li id='help'>
        <h4 class="footer-list-header">Redes Sociales</h4></li>
      <li><a class="generic-anchor footer-list-anchor">TWITTER</a></li>
      <li><a class="generic-anchor footer-list-anchor">INSTAGRAM</a></li>
      <li id='find-a-store'><a class="generic-anchor footer-list-anchor">FACEBOOK</a></li>
    </ul>


    <section class="footer-bottom-section flex-rw">
    <div class="footer-bottom-wrapper">

      <div class="footer-address">
        <p id="css_validar">
        <a href="http://jigsaw.w3.org/css-validator/check/referer">
            <img style="border:0;width:88px;height:31px"
                src="http://jigsaw.w3.org/css-validator/images/vcss-blue"
                alt="¡CSS Válido!" />
            </a>
        </p>
        <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
          <img class='footer-address_img' alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" />
        </a><br />
      </div>
      <div class="footer-address">
          <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Surface</span> by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Daniel González González</span>
          is licensed under a
          <a class="cretive_commons" rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
            Creative Commons Reconocimiento-NoComercial 4.0 Internacional License
          </a>.
      </div>

    </div>
    </section>
    </footer>
    </div>
  </body>
</html>
